config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :stores
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :products, except: [:destroy]
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence:true,
            uniqueness: {case_sensitive: false},
            length: {maximum:25}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :store_products
  has_many :stores, through: :store_products
  validates :name, presence: true, length: {maximum: 25 }
  validates :size, presence: true, length: {maximum: 25 }
  validates :price, presence: true, length: {maximum: 25 }
  validates_uniqueness_of :name
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :store_products
  has_many :products, through: :store_products
  validates :name, presence: true, length: {maximum: 100}
  validates :street, presence: true, length: {maximum: 100}
  validates :number, presence: true, length: {maximum: 100}
  validates :zip_code, presence: true, length: {maximum: 100}
  validates :city, presence: true, length: {maximum: 100}
  validates :country, presence: true, length: {maximum: 100}
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :store
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :stores, dependent: :destroy
  validates :username, presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum:3,maximum: 100}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: {case_sensitive: false},
            length: {maximum: 105},
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Product was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to category_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to stores_path if logged_in?
  end

  def about

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product was successfully created"
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product updated successfully"
      redirect_to @product
    else
      render 'edit'
    end
  end

  def index
    @products = Product.paginate(page: params[:page], per_page: 5)
  end

  def show
    @product = Product.find(params[:id])
    @stores = @product.stores.paginate(page: params[:page], per_page: 5)
  end

  private

  def product_params
    params.require(:product).permit(:name, :color, :size, :process, :category_id)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to product_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show

  end

  def index
    @stores = Store.paginate(page: params[:page], per_page: 5)
  end

  def new
    @store = Store.new
  end

  def edit

  end

  def create
    @store = Store.new(stores_params)
    @store.user = current_user
    if @store.save
      flash[:notice] = "Store was created successfully."
      redirect_to @store
    else
      render 'new'
    end
  end

  def update
    if @store.update(stores_params)
      flash[:notice] = "Store was updated successfully."
      redirect_to @store
    else
      render 'edit'
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path
  end

  private

  def set_category
    @store = Store.find(params[:id])
  end

  def stores_params
    params.require(:store).permit(:name, :street, :number, :zip_code, :city, :country, product_ids: [])
  end

  def require_same_user
    if current_user != @store.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own category"
      redirect_to @store
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @stores = @user.stores.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated stores successfully deleted"
    redirect_to stores_path
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}, you have successfully sign up"
      redirect_to stores_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(@category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj:@category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class:"form-control shadow rounded", placeholder:"Enter a name"  %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class:"btn btn-outline-light btn-lg" %>
        </div>
      <%end %>
    </div>
    <%= link_to '[Cancel and return to categories listing]', categories_path, class: "text-info" %>

  </div>

</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit product</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @products, :container => false %>
</div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.products.count, "products") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago,
              edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @products, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Products</h3>

<div class="flickr_pagination">
  <%= will_paginate @products, :container => false %>
</div>

<%= render 'products/list' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @products , :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Author: Joaquín Rivadeneira C.</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Full Stack Project", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%=link_to "Users",  users_path, class:"nav-link"%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Stores
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new store", new_store_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View stores", stores_path, class: "dropdown-item"%>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new product", new_product_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View products", products_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullStackProject</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">
<%= render 'layouts/navigation' %>
<div id="page-content">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h2>This is the About Page</h2>

<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Full Stack Project</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up!", signup_path, class:"btn btn-success btn-lg" %>
  </div>
</div>

app/views/products/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj:@product %>
      <%= form_with(model: @product, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class:"form-control shadow rounded", placeholder:"Enter a name"  %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :color, class: "col-2 col-form-label text-light" %> <br>
          <div class="col-10">
            <%= f.text_field :color,  class:"form-control shadow rounded", placeholder:"Enter color" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :size, class: "col-2 col-form-label text-light" %> <br>
          <div class="col-10">
            <%= f.text_field :size,  class:"form-control shadow rounded", placeholder:"Enter size" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :price, class: "col-2 col-form-label text-light" %> <br>
          <div class="col-10">
            <%= f.text_field :price,  class:"form-control shadow rounded", placeholder:"Enter price" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10" style="padding-top: 5px">
            <%= f.collection_select(:category_id, Category.all, :id, :name,
                                    {class: "custom-select shadow rounded" }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class:"btn btn-outline-light btn-lg" %>
        </div>
      <%end %>
    </div>
    <%= link_to '[Cancel and return to products listing]', products_path, class: "text-info" %>


  </div>

</div>

app/views/products/_list.html.erb
<div class="container">
  <% @products.each do |product| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to product.name, product_path(product), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(product.stores.count, "store") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(product.created_at) %> ago,
              edited <%= time_ago_in_words(product.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<%= link_to product.name, product_path(product), class: "badge badge-pill badge-info mr-1" %>

app/views/products/edit.html.erb
<h1 class="text-center mt-4">Edit product</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<h1 class="text-center mt-4">Products</h1>

<div class="flickr_pagination">
  <%= will_paginate @stores, :container => false %>
</div>
<%= render 'list' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @stores, :container => false %>
</div>

app/views/products/new.html.erb
<h1 class="text-center mt-4">Create a new product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1 class="text-center mt-4">Product: <%= @product.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit product", edit_product_path(@product), class: "btn btn-outline-info" %>
  </div>
<% end %>

<br>
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-body">
    <p class="card-text"><strong>Color: </strong><%= truncate(@product.color, length: 100) %></p>
    <p class="card-text"><strong>Size: </strong><%= truncate(@product.size, length: 100) %></p>
    <p class="card-text"><strong>Price: </strong>$<%= truncate(@product.price, length: 100) %></p>
    <p class="card-text"><strong>Category: </strong><%= @product.category.name %></p>

  </div>
</div>

<h3 class="text-center mt-4">Stores</h3>

<div class="flickr_pagination">
  <%= will_paginate @stores, :container => false %>
</div>

<%= render 'stores/store' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @stores , :container => false %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end %>

app/views/stores/_store.html.erb
<div class="container">
  <% @stores.each do |store| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if store.user %>
              by <%= link_to store.user.username, store_path(store.user) %>
            <% end %>
            <% if store.products.any? %>
              <p class="card-text"><strong>Products: </strong></p>
              <div class="mt-2"><%= render store.products %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to store.name, store_path(store), class: "text-success" %></h5>
            <p class="card-text"><strong>Street: </strong><%= truncate(store.street, length: 100) %></p>
            <p class="card-text"><strong>Number: </strong><%= truncate(store.number, length: 100) %></p>
            <p class="card-text"><strong>Zip Code: </strong><%= truncate(store.zip_code, length: 100) %></p>
            <p class="card-text"><strong>City: </strong><%= truncate(store.city, length: 100) %></p>
            <p class="card-text"><strong>Country: </strong><%= truncate(store.country, length: 100) %></p>
            <%= link_to "View", store_path(store), class: "btn btn-outline-success" %>
            <% if logged_in? && (store.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_store_path(store), class: "btn btn-outline-info" %>
              <%= link_to "Delete", store_path(store), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
         </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(store.created_at) %> ago,
              edited <%= time_ago_in_words(store.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/stores/edit.html.erb
<h1 class="text-center mt-4">Edit store</h1>
<%= render 'form' %>

app/views/stores/index.html.erb
<h1 class="text-center mt-4">Stores</h1>

<div class="flickr_pagination">
  <%= will_paginate @stores, :container => false %>
</div>
<%= render 'store' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @stores, :container => false %>
</div>

app/views/stores/new.html.erb
<h1 class="text-center mt-4">Create new store</h1>
<%= render 'form' %>

app/views/stores/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @store.name %></h2>

  <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              by <%=@store.user.username if @store.user%>
              <%= link_to gravatar_for(@store.user), user_path(@store.user) %>
              <% if @store.products.any? %>
                <p class="card-text"><strong>Products: </strong></p>
                <div class="mt-2"><%= render @store.products %></div>
              <% end %>
            </div>
            <div class="card-body">
              <p class="card-text"><strong>Street: </strong><%= truncate(@store.street, length: 100) %></p>
              <p class="card-text"><strong>Number: </strong><%= truncate(@store.number, length: 100) %></p>
              <p class="card-text"><strong>Zip Code: </strong><%= truncate(@store.zip_code, length: 100) %></p>
              <p class="card-text"><strong>City: </strong><%= truncate(@store.city, length: 100) %></p>
              <p class="card-text"><strong>Country: </strong><%= truncate(@store.country, length: 100) %></p>
              <% if logged_in? && (@store.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_store_path(@store), class: "btn btn-outline-info" %>
                <%= link_to "Delete", store_path(@store), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(@store.created_at) %> ago,
                edited <%= time_ago_in_words(@store.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%=link_to user.username, user%>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.stores.count, "stores") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%=@user.username %> profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>


<h3 class="text-center mt-4">Stores</h3>

<div class="flickr_pagination">
  <%= will_paginate @stores, :container => false %>
</div>

<%= render 'stores/store' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @stores, :container => false %>
</div>